{% set name = "swig" %}
{% set version = "4.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: swig-{{ version }}.tar.gz  # [unix]
  url: https://prdownloads.sourceforge.net/{{ name }}/{{ name }}-{{ version }}.tar.gz  # [unix]
  sha256: 2af08aced8fcd65cdb5cc62426768914bedc735b1c250325203716f78e39ac9b  # [unix]
  fn: swigwin-{{ version }}.zip  # [win]
  url: https://prdownloads.sourceforge.net/{{ name }}/{{ name }}win-{{ version }}.zip  # [win]
  sha256: 2ec3107e24606db535d77ef3dbf246dc6eccbf1d5c868dce365d7f7fb19a1a51  # [win]

build:
  number: 0
  detect_binary_files_with_prefix: True  # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make     # [unix]
    - libtool  # [unix]
  host:        # [unix]
    - pcre2    # [unix]
    - zlib     # [unix]
  run:         # [unix]
    - pcre2    # [unix]

test:
  commands:
    - swig -help
    - swig -swiglib

about:
  home: https://www.swig.org/
  license: GPL-3.0-or-later
  license_file: LICENSE
  license_family: GPL
  summary: C/C++ parser code generator
  description: |
    SWIG is an interface compiler that connects programs written in C and C++
    with scripting languages such as Perl, Python, Ruby, and Tcl. It works by
    taking the declarations found in C/C++ header files and using them to
    generate the wrapper code that scripting languages need to access the
    underlying C/C++ code. In addition, SWIG provides a variety of
    customization features that let you tailor the wrapping process to suit
    your application.
  dev_url: https://github.com/swig/swig
  doc_url: https://www.swig.org/doc.html

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
    - mingwandroid
    - msarahan
    - ocefpaf

  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/42154
    reason: Built for customer - see ticket
    recipe-maintainers:
      - bkreider

